---
- hosts: localhost
  tasks:

  - name: Define data to work on in the examples below
    ansible.builtin.set_fact:
      domain_definition:
        domain:
          cluster:
            - name: cluster1
            - name: cluster2
          server:
            - name: server11
              cluster: cluster1
              port: '8080'
            - name: server12
              cluster: cluster1
              port: '8090'
            - name: server21
              cluster: cluster2
              port: '9080'
            - name: server22
              cluster: cluster2
              port: '9090'
          library:
            - name: lib1
              target: cluster1
            - name: lib2
              target: cluster2

  - name: Display all cluster names
    ansible.builtin.debug:
      var: item
    loop: "{{ domain_definition | json_query('domain.cluster[*].name') }}"
